import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { Globe } from 'lucide-react';

const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' }
];

const CONTENT = {
  en: {
    title: "Terms and Conditions",
    lastUpdated: "Last updated: January 2025",
    content: `
      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using MyWellness (the "Service"), operated by VELIKA GROUP LLC ("we", "our"), the user ("you", "your") agrees to be bound by these Terms and Conditions. If you do not accept these terms, do not use the Service.</p>

      <h2>2. Service Description</h2>
      <p>MyWellness provides personalized nutrition and workout plans generated through artificial intelligence. The Service includes body analysis, progress tracking, personalized recipes and workout routines.</p>

      <h2>3. Subscriptions and Payments</h2>
      <p><strong>3.1 Trial Period:</strong> We offer a 3-day free trial period. During this period, no charges will be made. You can cancel at any time before the trial period expires.</p>
      <p><strong>3.2 Automatic Renewal:</strong> At the end of the trial period, the subscription will automatically renew to the selected plan (Base, Pro or Premium) with monthly or annual billing according to your choice.</p>
      <p><strong>3.3 Pricing:</strong> Prices are shown in Euro (€) and may vary. The applicable price is the one displayed at the time of purchase.</p>
      <p><strong>3.4 Cancellation:</strong> You can cancel your subscription at any time through your account settings. The cancellation will take effect at the end of the current billing period.</p>

      <h2>4. User Account</h2>
      <p><strong>4.1 Registration:</strong> To use the Service, you must create an account by providing accurate and complete information.</p>
      <p><strong>4.2 Security:</strong> You are responsible for the security of your account and the confidentiality of your login credentials.</p>
      <p><strong>4.3 Minimum Age:</strong> You must be at least 18 years old to use the Service. If you are under 18 years old, you must obtain parental or guardian consent.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree to:</p>
      <ul>
        <li>Use the Service only for personal and non-commercial purposes</li>
        <li>Provide accurate information about your health profile</li>
        <li>Not share your account with other people</li>
        <li>Not use the Service for illegal or unauthorized activities</li>
        <li>Not attempt to breach the security of the Service</li>
      </ul>

      <h2>6. Medical Disclaimer</h2>
      <p><strong>IMPORTANT:</strong> MyWellness does NOT provide medical advice. The nutrition and workout plans are generated by artificial intelligence and are for informational and educational purposes only.</p>
      <p>Before starting any nutrition or exercise program, consult your doctor or a qualified healthcare professional, especially if you have pre-existing medical conditions, are pregnant, nursing or taking medication.</p>
      <p>Use of the Service is at your own risk and responsibility.</p>

      <h2>7. Intellectual Property</h2>
      <p>All content, software, code, design, graphics, logos and materials present in the Service are the exclusive property of VELIKA GROUP LLC and are protected by copyright, trademarks and other intellectual property laws.</p>

      <h2>8. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, VELIKA GROUP LLC will not be liable for:</p>
      <ul>
        <li>Direct, indirect, incidental, consequential or punitive damages</li>
        <li>Loss of profits, data or business opportunities</li>
        <li>Physical injury or health damage resulting from use of the Service</li>
        <li>Interruptions or errors in the Service</li>
        <li>Third party content or behavior</li>
      </ul>

      <h2>9. Changes to Terms</h2>
      <p>We reserve the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

      <h2>10. Termination</h2>
      <p>We reserve the right to suspend or terminate your account in case of violation of these Terms, without notice and without refund.</p>

      <h2>11. Applicable Law</h2>
      <p>These Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict of law principles.</p>

      <h2>12. Contact</h2>
      <p>For questions about these Terms and Conditions, contact us:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>Email: velika.03@outlook.it</p>
      </div>
    `
  },
  it: {
    title: "Termini e Condizioni",
    lastUpdated: "Ultimo aggiornamento: Gennaio 2025",
    content: `
      <h2>1. Accettazione dei Termini</h2>
      <p>Accedendo e utilizzando MyWellness (il "Servizio"), gestito da VELIKA GROUP LLC ("noi", "nostro"), l'utente ("tu", "tuo") accetta di essere vincolato da questi Termini e Condizioni. Se non accetti questi termini, non utilizzare il Servizio.</p>

      <h2>2. Descrizione del Servizio</h2>
      <p>MyWellness fornisce piani nutrizionali e di allenamento personalizzati generati tramite intelligenza artificiale. Il Servizio include analisi del corpo, monitoraggio dei progressi, ricette personalizzate e schede di allenamento.</p>

      <h2>3. Abbonamenti e Pagamenti</h2>
      <p><strong>3.1 Periodo di Prova:</strong> Offriamo un periodo di prova gratuito di 3 giorni. Durante questo periodo, non verranno effettuati addebiti. Puoi cancellare in qualsiasi momento prima della scadenza del periodo di prova.</p>
      <p><strong>3.2 Rinnovo Automatico:</strong> Alla scadenza del periodo di prova, l'abbonamento si rinnoverà automaticamente al piano selezionato (Base, Pro o Premium) con fatturazione mensile o annuale secondo la tua scelta.</p>
      <p><strong>3.3 Prezzi:</strong> I prezzi sono indicati in Euro (€) e possono variare. Il prezzo applicabile è quello visualizzato al momento dell'acquisto.</p>
      <p><strong>3.4 Cancellazione:</strong> Puoi cancellare il tuo abbonamento in qualsiasi momento attraverso le impostazioni del tuo account. La cancellazione avrà effetto alla fine del periodo di fatturazione corrente.</p>

      <h2>4. Account Utente</h2>
      <p><strong>4.1 Registrazione:</strong> Per utilizzare il Servizio, devi creare un account fornendo informazioni accurate e complete.</p>
      <p><strong>4.2 Sicurezza:</strong> Sei responsabile della sicurezza del tuo account e della riservatezza delle tue credenziali di accesso.</p>
      <p><strong>4.3 Età Minima:</strong> Devi avere almeno 18 anni per utilizzare il Servizio. Se hai meno di 18 anni, devi ottenere il consenso di un genitore o tutore.</p>

      <h2>5. Uso Accettabile</h2>
      <p>Ti impegni a:</p>
      <ul>
        <li>Utilizzare il Servizio solo per scopi personali e non commerciali</li>
        <li>Fornire informazioni accurate sul tuo profilo di salute</li>
        <li>Non condividere il tuo account con altre persone</li>
        <li>Non utilizzare il Servizio per attività illegali o non autorizzate</li>
        <li>Non tentare di violare la sicurezza del Servizio</li>
      </ul>

      <h2>6. Disclaimer Medico</h2>
      <p><strong>IMPORTANTE:</strong> MyWellness NON fornisce consulenza medica. I piani nutrizionali e di allenamento sono generati da intelligenza artificiale e hanno esclusivamente scopo informativo ed educativo.</p>
      <p>Prima di iniziare qualsiasi programma nutrizionale o di esercizio fisico, consulta il tuo medico o un professionista sanitario qualificato, specialmente se hai condizioni mediche preesistenti, sei in gravidanza, allatti o assumi farmaci.</p>
      <p>L'uso del Servizio è a tuo esclusivo rischio e responsabilità.</p>

      <h2>7. Proprietà Intellettuale</h2>
      <p>Tutti i contenuti, software, codice, design, grafica, logo e materiali presenti nel Servizio sono di proprietà esclusiva di VELIKA GROUP LLC e sono protetti da copyright, marchi e altre leggi sulla proprietà intellettuale.</p>

      <h2>8. Limitazione di Responsabilità</h2>
      <p>Nella misura massima consentita dalla legge, VELIKA GROUP LLC non sarà responsabile per:</p>
      <ul>
        <li>Danni diretti, indiretti, incidentali, consequenziali o punitivi</li>
        <li>Perdita di profitti, dati o opportunità commerciali</li>
        <li>Lesioni fisiche o danni alla salute derivanti dall'uso del Servizio</li>
        <li>Interruzioni o errori nel Servizio</li>
        <li>Contenuti o comportamenti di terze parti</li>
      </ul>

      <h2>9. Modifiche ai Termini</h2>
      <p>Ci riserviamo il diritto di modificare questi Termini e Condizioni in qualsiasi momento. Le modifiche saranno effettive immediatamente dopo la pubblicazione. L'uso continuato del Servizio dopo le modifiche costituisce accettazione dei nuovi termini.</p>

      <h2>10. Risoluzione</h2>
      <p>Ci riserviamo il diritto di sospendere o terminare il tuo account in caso di violazione di questi Termini, senza preavviso e senza rimborso.</p>

      <h2>11. Legge Applicabile</h2>
      <p>Questi Termini sono regolati dalle leggi dello Stato del Wyoming, Stati Uniti, senza riguardo ai principi sui conflitti di legge.</p>

      <h2>12. Contatti</h2>
      <p>Per domande su questi Termini e Condizioni, contattaci:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>Email: velika.03@outlook.it</p>
      </div>
    `
  },
  es: {
    title: "Términos y Condiciones",
    lastUpdated: "Última actualización: Enero 2025",
    content: `<h2>1. Aceptación de los Términos</h2><p>Al acceder y utilizar MyWellness...</p>`
  },
  pt: {
    title: "Termos e Condições",
    lastUpdated: "Última atualização: Janeiro 2025",
    content: `<h2>1. Aceitação dos Termos</h2><p>Ao acessar e usar MyWellness...</p>`
  },
  de: {
    title: "Allgemeine Geschäftsbedingungen",
    lastUpdated: "Letzte Aktualisierung: Januar 2025",
    content: `<h2>1. Annahme der Bedingungen</h2><p>Durch den Zugriff und die Nutzung von MyWellness...</p>`
  },
  fr: {
    title: "Termes et Conditions",
    lastUpdated: "Dernière mise à jour: Janvier 2025",
    content: `<h2>1. Acceptation des Conditions</h2><p>En accédant et en utilisant MyWellness...</p>`
  }
};

export default function Terms() {
  const navigate = useNavigate();
  const [selectedLang, setSelectedLang] = useState('en');
  const [langMenuOpen, setLangMenuOpen] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const content = CONTENT[selectedLang];

  return (
    <div className="min-h-screen overflow-x-hidden animated-gradient-bg">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
        * { font-family: 'Inter', sans-serif; }
        :root {
          --brand-primary: #26847F;
          --brand-primary-hover: #1f6b66;
          --brand-primary-light: #e9f6f5;
        }
        .water-glass-effect {
          backdrop-filter: blur(12px) saturate(180%);
          background: linear-gradient(135deg, rgba(249, 250, 251, 0.75) 0%, rgba(243, 244, 246, 0.65) 50%, rgba(249, 250, 251, 0.75) 100%);
          box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.08), inset 0 1px 1px 0 rgba(255, 255, 255, 0.9), inset 0 -1px 1px 0 rgba(0, 0, 0, 0.05);
        }
        .content h2 { font-size: 1.5rem; font-weight: bold; color: #111827; margin-top: 2rem; margin-bottom: 1rem; }
        .content h3 { font-size: 1.25rem; font-weight: 600; color: #111827; margin-top: 1.5rem; margin-bottom: 0.75rem; }
        .content ul { list-style: disc; padding-left: 1.5rem; margin: 0.5rem 0; }
        .content li { margin: 0.5rem 0; }
        .content p { margin: 0.75rem 0; }
        .content a { color: var(--brand-primary); text-decoration: underline; }
        .contact-box { background: #f9fafb; padding: 1rem; border-radius: 0.5rem; margin-top: 1rem; }
      `}</style>

      {/* Navbar */}
      <nav className="fixed top-6 left-1/2 transform -translate-x-1/2 z-50 px-4 w-full max-w-[300px]">
        <div className="water-glass-effect rounded-full px-6 py-3 flex justify-center">
          <img
            src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68d44c626cc2c19cca9c750d/c3567e77e_MyWellnesslogo.png"
            alt="MyWellness"
            className="h-6 cursor-pointer"
            onClick={() => navigate(createPageUrl('Home'))}
          />
        </div>
      </nav>

      {/* Main Content */}
      <div className="pt-32 pb-20 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto water-glass-effect rounded-3xl p-6 sm:p-8 md:p-12">
          {/* Language Selector */}
          <div className="flex justify-end mb-6">
            <div className="relative">
              <button
                onClick={() => setLangMenuOpen(!langMenuOpen)}
                className="flex items-center gap-2 px-4 py-2 bg-white/80 hover:bg-white rounded-full border border-gray-200 transition-all">
                <Globe className="w-4 h-4 text-gray-600" />
                <span className="text-sm font-medium text-gray-700">
                  {LANGUAGES.find(l => l.code === selectedLang)?.flag} {LANGUAGES.find(l => l.code === selectedLang)?.name}
                </span>
              </button>

              {langMenuOpen && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setLangMenuOpen(false)}></div>
                  <div className="absolute right-0 top-12 bg-white rounded-2xl border border-gray-200 shadow-xl p-2 min-w-[180px] z-50">
                    {LANGUAGES.map((lang) => (
                      <button
                        key={lang.code}
                        onClick={() => {
                          setSelectedLang(lang.code);
                          setLangMenuOpen(false);
                        }}
                        className={`w-full text-left px-3 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 ${
                          selectedLang === lang.code
                            ? 'bg-[var(--brand-primary)] text-white'
                            : 'text-gray-700 hover:bg-gray-50'
                        }`}>
                        <span className="text-lg">{lang.flag}</span>
                        <span>{lang.name}</span>
                      </button>
                    ))}
                  </div>
                </>
              )}
            </div>
          </div>

          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-6 sm:mb-8">{content.title}</h1>
          <p className="text-xs sm:text-sm text-gray-500 mb-6 sm:mb-8">{content.lastUpdated}</p>

          <div 
            className="content space-y-6 sm:space-y-8 text-sm sm:text-base text-gray-700 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: content.content }}
          />
        </div>
      </div>

      {/* Footer */}
      <footer className="py-12 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center space-y-2">
            <p className="text-sm font-semibold text-gray-700">
              © VELIKA GROUP LLC. All Rights Reserved.
            </p>
            <p className="text-xs text-gray-500">
              30 N Gould St 32651 Sheridan, WY 82801, United States
            </p>
            <p className="text-xs text-gray-500">
              EIN: 36-5141800 - velika.03@outlook.it
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}