import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { Globe } from 'lucide-react';

const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' }
];

const CONTENT = {
  en: {
    title: "Terms and Conditions",
    lastUpdated: "Last updated: January 2025",
    content: `
      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using MyWellness (the "Service"), operated by VELIKA GROUP LLC ("we", "our"), the user ("you", "your") agrees to be bound by these Terms and Conditions. If you do not accept these terms, do not use the Service.</p>

      <h2>2. Service Description</h2>
      <p>MyWellness provides personalized nutrition and workout plans generated through artificial intelligence. The Service includes body analysis, progress tracking, personalized recipes and workout routines.</p>

      <h2>3. Subscriptions and Payments</h2>
      <p><strong>3.1 Trial Period:</strong> We offer a 3-day free trial period. During this period, no charges will be made. You can cancel at any time before the trial period expires.</p>
      <p><strong>3.2 Automatic Renewal:</strong> At the end of the trial period, the subscription will automatically renew to the selected plan (Base, Pro or Premium) with monthly or annual billing according to your choice.</p>
      <p><strong>3.3 Pricing:</strong> Prices are shown in Euro (€) and may vary. The applicable price is the one displayed at the time of purchase.</p>
      <p><strong>3.4 Cancellation:</strong> You can cancel your subscription at any time through your account settings. The cancellation will take effect at the end of the current billing period.</p>

      <h2>4. User Account</h2>
      <p><strong>4.1 Registration:</strong> To use the Service, you must create an account by providing accurate and complete information.</p>
      <p><strong>4.2 Security:</strong> You are responsible for the security of your account and the confidentiality of your login credentials.</p>
      <p><strong>4.3 Minimum Age:</strong> You must be at least 18 years old to use the Service. If you are under 18 years old, you must obtain parental or guardian consent.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree to:</p>
      <ul>
        <li>Use the Service only for personal and non-commercial purposes</li>
        <li>Provide accurate information about your health profile</li>
        <li>Not share your account with other people</li>
        <li>Not use the Service for illegal or unauthorized activities</li>
        <li>Not attempt to breach the security of the Service</li>
      </ul>

      <h2>6. Medical Disclaimer</h2>
      <p><strong>IMPORTANT:</strong> MyWellness does NOT provide medical advice. The nutrition and workout plans are generated by artificial intelligence and are for informational and educational purposes only.</p>
      <p>Before starting any nutrition or exercise program, consult your doctor or a qualified healthcare professional, especially if you have pre-existing medical conditions, are pregnant, nursing or taking medication.</p>
      <p>Use of the Service is at your own risk and responsibility.</p>

      <h2>7. Intellectual Property</h2>
      <p>All content, software, code, design, graphics, logos and materials present in the Service are the exclusive property of VELIKA GROUP LLC and are protected by copyright, trademarks and other intellectual property laws.</p>

      <h2>8. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, VELIKA GROUP LLC will not be liable for:</p>
      <ul>
        <li>Direct, indirect, incidental, consequential or punitive damages</li>
        <li>Loss of profits, data or business opportunities</li>
        <li>Physical injury or health damage resulting from use of the Service</li>
        <li>Interruptions or errors in the Service</li>
        <li>Third party content or behavior</li>
      </ul>

      <h2>9. Changes to Terms</h2>
      <p>We reserve the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

      <h2>10. Termination</h2>
      <p>We reserve the right to suspend or terminate your account in case of violation of these Terms, without notice and without refund.</p>

      <h2>11. Applicable Law</h2>
      <p>These Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict of law principles.</p>

      <h2>12. Contact</h2>
      <p>For questions about these Terms and Conditions, contact us:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>Email: velika.03@outlook.it</p>
      </div>
    `
  },
  it: {
    title: "Termini e Condizioni",
    lastUpdated: "Ultimo aggiornamento: Gennaio 2025",
    content: `
      <h2>1. Accettazione dei Termini</h2>
      <p>Accedendo e utilizzando MyWellness (il "Servizio"), gestito da VELIKA GROUP LLC ("noi", "nostro"), l'utente ("tu", "tuo") accetta di essere vincolato da questi Termini e Condizioni. Se non accetti questi termini, non utilizzare il Servizio.</p>

      <h2>2. Descrizione del Servizio</h2>
      <p>MyWellness fornisce piani nutrizionali e di allenamento personalizzati generati tramite intelligenza artificiale. Il Servizio include analisi del corpo, monitoraggio dei progressi, ricette personalizzate e schede di allenamento.</p>

      <h2>3. Abbonamenti e Pagamenti</h2>
      <p><strong>3.1 Periodo di Prova:</strong> Offriamo un periodo di prova gratuito di 3 giorni. Durante questo periodo, non verranno effettuati addebiti. Puoi cancellare in qualsiasi momento prima della scadenza del periodo di prova.</p>
      <p><strong>3.2 Rinnovo Automatico:</strong> Alla scadenza del periodo di prova, l'abbonamento si rinnoverà automaticamente al piano selezionato (Base, Pro o Premium) con fatturazione mensile o annuale secondo la tua scelta.</p>
      <p><strong>3.3 Prezzi:</strong> I prezzi sono indicati in Euro (€) e possono variare. Il prezzo applicabile è quello visualizzato al momento dell'acquisto.</p>
      <p><strong>3.4 Cancellazione:</strong> Puoi cancellare il tuo abbonamento in qualsiasi momento attraverso le impostazioni del tuo account. La cancellazione avrà effetto alla fine del periodo di fatturazione corrente.</p>

      <h2>4. Account Utente</h2>
      <p><strong>4.1 Registrazione:</strong> Per utilizzare il Servizio, devi creare un account fornendo informazioni accurate e complete.</p>
      <p><strong>4.2 Sicurezza:</strong> Sei responsabile della sicurezza del tuo account e della riservatezza delle tue credenziali di accesso.</p>
      <p><strong>4.3 Età Minima:</strong> Devi avere almeno 18 anni per utilizzare il Servizio. Se hai meno di 18 anni, devi ottenere il consenso di un genitore o tutore.</p>

      <h2>5. Uso Accettabile</h2>
      <p>Ti impegni a:</p>
      <ul>
        <li>Utilizzare il Servizio solo per scopi personali e non commerciali</li>
        <li>Fornire informazioni accurate sul tuo profilo di salute</li>
        <li>Non condividere il tuo account con altre persone</li>
        <li>Non utilizzare il Servizio per attività illegali o non autorizzate</li>
        <li>Non tentare di violare la sicurezza del Servizio</li>
      </ul>

      <h2>6. Disclaimer Medico</h2>
      <p><strong>IMPORTANTE:</strong> MyWellness NON fornisce consulenza medica. I piani nutrizionali e di allenamento sono generati da intelligenza artificiale e hanno esclusivamente scopo informativo ed educativo.</p>
      <p>Prima di iniziare qualsiasi programma nutrizionale o di esercizio fisico, consulta il tuo medico o un professionista sanitario qualificato, specialmente se hai condizioni mediche preesistenti, sei in gravidanza, allatti o assumi farmaci.</p>
      <p>L'uso del Servizio è a tuo esclusivo rischio e responsabilità.</p>

      <h2>7. Proprietà Intellettuale</h2>
      <p>Tutti i contenuti, software, codice, design, grafica, logo e materiali presenti nel Servizio sono di proprietà esclusiva di VELIKA GROUP LLC e sono protetti da copyright, marchi e altre leggi sulla proprietà intellettuale.</p>

      <h2>8. Limitazione di Responsabilità</h2>
      <p>Nella misura massima consentita dalla legge, VELIKA GROUP LLC non sarà responsabile per:</p>
      <ul>
        <li>Danni diretti, indiretti, incidentali, consequenziali o punitivi</li>
        <li>Perdita di profitti, dati o opportunità commerciali</li>
        <li>Lesioni fisiche o danni alla salute derivanti dall'uso del Servizio</li>
        <li>Interruzioni o errori nel Servizio</li>
        <li>Contenuti o comportamenti di terze parti</li>
      </ul>

      <h2>9. Modifiche ai Termini</h2>
      <p>Ci riserviamo il diritto di modificare questi Termini e Condizioni in qualsiasi momento. Le modifiche saranno effettive immediatamente dopo la pubblicazione. L'uso continuato del Servizio dopo le modifiche costituisce accettazione dei nuovi termini.</p>

      <h2>10. Risoluzione</h2>
      <p>Ci riserviamo il diritto di sospendere o terminare il tuo account in caso di violazione di questi Termini, senza preavviso e senza rimborso.</p>

      <h2>11. Legge Applicabile</h2>
      <p>Questi Termini sono regolati dalle leggi dello Stato del Wyoming, Stati Uniti, senza riguardo ai principi sui conflitti di legge.</p>

      <h2>12. Contatti</h2>
      <p>Per domande su questi Termini e Condizioni, contattaci:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>Email: velika.03@outlook.it</p>
      </div>
    `
  },
  es: {
    title: "Términos y Condiciones",
    lastUpdated: "Última actualización: Enero 2025",
    content: `
      <h2>1. Aceptación de los Términos</h2>
      <p>Al acceder y utilizar MyWellness (el "Servicio"), operado por VELIKA GROUP LLC ("nosotros", "nuestro"), el usuario ("tú", "tu") acepta estar sujeto a estos Términos y Condiciones. Si no aceptas estos términos, no utilices el Servicio.</p>

      <h2>2. Descripción del Servicio</h2>
      <p>MyWellness proporciona planes nutricionales y de entrenamiento personalizados generados mediante inteligencia artificial. El Servicio incluye análisis corporal, seguimiento de progreso, recetas personalizadas y rutinas de entrenamiento.</p>

      <h2>3. Suscripciones y Pagos</h2>
      <p><strong>3.1 Período de Prueba:</strong> Ofrecemos un período de prueba gratuito de 3 días. Durante este período, no se realizarán cargos. Puedes cancelar en cualquier momento antes de que expire el período de prueba.</p>
      <p><strong>3.2 Renovación Automática:</strong> Al final del período de prueba, la suscripción se renovará automáticamente al plan seleccionado (Base, Pro o Premium) con facturación mensual o anual según tu elección.</p>
      <p><strong>3.3 Precios:</strong> Los precios se muestran en Euros (€) y pueden variar. El precio aplicable es el que se muestra en el momento de la compra.</p>
      <p><strong>3.4 Cancelación:</strong> Puedes cancelar tu suscripción en cualquier momento a través de la configuración de tu cuenta. La cancelación tendrá efecto al final del período de facturación actual.</p>

      <h2>4. Cuenta de Usuario</h2>
      <p><strong>4.1 Registro:</strong> Para utilizar el Servicio, debes crear una cuenta proporcionando información precisa y completa.</p>
      <p><strong>4.2 Seguridad:</strong> Eres responsable de la seguridad de tu cuenta y de la confidencialidad de tus credenciales de inicio de sesión.</p>
      <p><strong>4.3 Edad Mínima:</strong> Debes tener al menos 18 años para utilizar el Servicio. Si tienes menos de 18 años, debes obtener el consentimiento de un padre o tutor.</p>

      <h2>5. Uso Aceptable</h2>
      <p>Te comprometes a:</p>
      <ul>
        <li>Utilizar el Servicio solo para fines personales y no comerciales</li>
        <li>Proporcionar información precisa sobre tu perfil de salud</li>
        <li>No compartir tu cuenta con otras personas</li>
        <li>No utilizar el Servicio para actividades ilegales o no autorizadas</li>
        <li>No intentar violar la seguridad del Servicio</li>
      </ul>

      <h2>6. Exención de Responsabilidad Médica</h2>
      <p><strong>IMPORTANTE:</strong> MyWellness NO proporciona asesoramiento médico. Los planes nutricionales y de entrenamiento son generados por inteligencia artificial y son solo para fines informativos y educativos.</p>
      <p>Antes de comenzar cualquier programa nutricional o de ejercicio, consulta a tu médico o a un profesional de la salud calificado, especialmente si tienes condiciones médicas preexistentes, estás embarazada, amamantando o tomando medicamentos.</p>
      <p>El uso del Servicio es bajo tu propio riesgo y responsabilidad.</p>

      <h2>7. Propiedad Intelectual</h2>
      <p>Todo el contenido, software, código, diseño, gráficos, logotipos y materiales presentes en el Servicio son propiedad exclusiva de VELIKA GROUP LLC y están protegidos por derechos de autor, marcas registradas y otras leyes de propiedad intelectual.</p>

      <h2>8. Limitación de Responsabilidad</h2>
      <p>En la máxima medida permitida por la ley, VELIKA GROUP LLC no será responsable de:</p>
      <ul>
        <li>Daños directos, indirectos, incidentales, consecuentes o punitivos</li>
        <li>Pérdida de beneficios, datos u oportunidades comerciales</li>
        <li>Lesiones físicas o daños a la salud resultantes del uso del Servicio</li>
        <li>Interrupciones o errores en el Servicio</li>
        <li>Contenido o comportamiento de terceros</li>
      </ul>

      <h2>9. Modificaciones a los Términos</h2>
      <p>Nos reservamos el derecho de modificar estos Términos y Condiciones en cualquier momento. Los cambios serán efectivos inmediatamente después de su publicación. El uso continuado del Servicio después de los cambios constituye aceptación de los nuevos términos.</p>

      <h2>10. Terminación</h2>
      <p>Nos reservamos el derecho de suspender o terminar tu cuenta en caso de violación de estos Términos, sin previo aviso y sin reembolso.</p>

      <h2>11. Ley Aplicable</h2>
      <p>Estos Términos se rigen por las leyes del Estado de Wyoming, Estados Unidos, sin consideración a los principios de conflictos de leyes.</p>

      <h2>12. Contacto</h2>
      <p>Para preguntas sobre estos Términos y Condiciones, contáctanos:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>Email: velika.03@outlook.it</p>
      </div>
    `
  },
  pt: {
    title: "Termos e Condições",
    lastUpdated: "Última atualização: Janeiro 2025",
    content: `
      <h2>1. Aceitação dos Termos</h2>
      <p>Ao acessar e usar MyWellness (o "Serviço"), operado pela VELIKA GROUP LLC ("nós", "nosso"), o usuário ("você", "seu") concorda em estar vinculado a estes Termos e Condições. Se você não aceitar estes termos, não use o Serviço.</p>

      <h2>2. Descrição do Serviço</h2>
      <p>MyWellness fornece planos nutricionais e de treino personalizados gerados através de inteligência artificial. O Serviço inclui análise corporal, acompanhamento de progresso, receitas personalizadas e rotinas de treino.</p>

      <h2>3. Assinaturas e Pagamentos</h2>
      <p><strong>3.1 Período de Teste:</strong> Oferecemos um período de teste gratuito de 3 dias. Durante este período, não serão feitas cobranças. Você pode cancelar a qualquer momento antes que o período de teste expire.</p>
      <p><strong>3.2 Renovação Automática:</strong> Ao final do período de teste, a assinatura será renovada automaticamente para o plano selecionado (Base, Pro ou Premium) com faturamento mensal ou anual de acordo com sua escolha.</p>
      <p><strong>3.3 Preços:</strong> Os preços são mostrados em Euros (€) e podem variar. O preço aplicável é o exibido no momento da compra.</p>
      <p><strong>3.4 Cancelamento:</strong> Você pode cancelar sua assinatura a qualquer momento através das configurações da sua conta. O cancelamento terá efeito no final do período de faturamento atual.</p>

      <h2>4. Conta de Usuário</h2>
      <p><strong>4.1 Registro:</strong> Para usar o Serviço, você deve criar uma conta fornecendo informações precisas e completas.</p>
      <p><strong>4.2 Segurança:</strong> Você é responsável pela segurança da sua conta e pela confidencialidade das suas credenciais de login.</p>
      <p><strong>4.3 Idade Mínima:</strong> Você deve ter pelo menos 18 anos para usar o Serviço. Se você tiver menos de 18 anos, deve obter o consentimento de um pai ou responsável.</p>

      <h2>5. Uso Aceitável</h2>
      <p>Você concorda em:</p>
      <ul>
        <li>Usar o Serviço apenas para fins pessoais e não comerciais</li>
        <li>Fornecer informações precisas sobre seu perfil de saúde</li>
        <li>Não compartilhar sua conta com outras pessoas</li>
        <li>Não usar o Serviço para atividades ilegais ou não autorizadas</li>
        <li>Não tentar violar a segurança do Serviço</li>
      </ul>

      <h2>6. Isenção de Responsabilidade Médica</h2>
      <p><strong>IMPORTANTE:</strong> MyWellness NÃO fornece aconselhamento médico. Os planos nutricionais e de treino são gerados por inteligência artificial e são apenas para fins informativos e educacionais.</p>
      <p>Antes de iniciar qualquer programa nutricional ou de exercícios, consulte seu médico ou um profissional de saúde qualificado, especialmente se você tiver condições médicas preexistentes, estiver grávida, amamentando ou tomando medicamentos.</p>
      <p>O uso do Serviço é por sua conta e risco.</p>

      <h2>7. Propriedade Intelectual</h2>
      <p>Todo o conteúdo, software, código, design, gráficos, logotipos e materiais presentes no Serviço são propriedade exclusiva da VELIKA GROUP LLC e são protegidos por direitos autorais, marcas registradas e outras leis de propriedade intelectual.</p>

      <h2>8. Limitação de Responsabilidade</h2>
      <p>Na máxima extensão permitida por lei, a VELIKA GROUP LLC não será responsável por:</p>
      <ul>
        <li>Danos diretos, indiretos, incidentais, consequenciais ou punitivos</li>
        <li>Perda de lucros, dados ou oportunidades comerciais</li>
        <li>Lesões físicas ou danos à saúde resultantes do uso do Serviço</li>
        <li>Interrupções ou erros no Serviço</li>
        <li>Conteúdo ou comportamento de terceiros</li>
      </ul>

      <h2>9. Modificações aos Termos</h2>
      <p>Reservamo-nos o direito de modificar estes Termos e Condições a qualquer momento. As alterações serão efetivas imediatamente após a publicação. O uso continuado do Serviço após as alterações constitui aceitação dos novos termos.</p>

      <h2>10. Rescisão</h2>
      <p>Reservamo-nos o direito de suspender ou encerrar sua conta em caso de violação destes Termos, sem aviso prévio e sem reembolso.</p>

      <h2>11. Lei Aplicável</h2>
      <p>Estes Termos são regidos pelas leis do Estado de Wyoming, Estados Unidos, sem considerar os princípios de conflito de leis.</p>

      <h2>12. Contato</h2>
      <p>Para perguntas sobre estes Termos e Condições, entre em contato conosco:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>Email: velika.03@outlook.it</p>
      </div>
    `
  },
  de: {
    title: "Allgemeine Geschäftsbedingungen",
    lastUpdated: "Letzte Aktualisierung: Januar 2025",
    content: `
      <h2>1. Annahme der Bedingungen</h2>
      <p>Durch den Zugriff und die Nutzung von MyWellness (der "Dienst"), betrieben von VELIKA GROUP LLC ("wir", "unser"), stimmt der Nutzer ("Sie", "Ihr") zu, an diese Allgemeinen Geschäftsbedingungen gebunden zu sein. Wenn Sie diese Bedingungen nicht akzeptieren, nutzen Sie den Dienst nicht.</p>

      <h2>2. Beschreibung des Dienstes</h2>
      <p>MyWellness bietet personalisierte Ernährungs- und Trainingspläne, die durch künstliche Intelligenz generiert werden. Der Dienst umfasst Körperanalyse, Fortschrittsverfolgung, personalisierte Rezepte und Trainingsroutinen.</p>

      <h2>3. Abonnements und Zahlungen</h2>
      <p><strong>3.1 Testzeitraum:</strong> Wir bieten einen 3-tägigen kostenlosen Testzeitraum an. Während dieses Zeitraums werden keine Gebühren erhoben. Sie können jederzeit vor Ablauf des Testzeitraums kündigen.</p>
      <p><strong>3.2 Automatische Verlängerung:</strong> Am Ende des Testzeitraums verlängert sich das Abonnement automatisch auf den gewählten Plan (Base, Pro oder Premium) mit monatlicher oder jährlicher Abrechnung gemäß Ihrer Wahl.</p>
      <p><strong>3.3 Preise:</strong> Die Preise werden in Euro (€) angezeigt und können variieren. Der gültige Preis ist der zum Zeitpunkt des Kaufs angezeigte.</p>
      <p><strong>3.4 Kündigung:</strong> Sie können Ihr Abonnement jederzeit über Ihre Kontoeinstellungen kündigen. Die Kündigung wird am Ende des aktuellen Abrechnungszeitraums wirksam.</p>

      <h2>4. Benutzerkonto</h2>
      <p><strong>4.1 Registrierung:</strong> Um den Dienst zu nutzen, müssen Sie ein Konto erstellen und genaue und vollständige Informationen angeben.</p>
      <p><strong>4.2 Sicherheit:</strong> Sie sind für die Sicherheit Ihres Kontos und die Vertraulichkeit Ihrer Anmeldedaten verantwortlich.</p>
      <p><strong>4.3 Mindestalter:</strong> Sie müssen mindestens 18 Jahre alt sein, um den Dienst zu nutzen. Wenn Sie unter 18 Jahre alt sind, müssen Sie die Zustimmung eines Elternteils oder Erziehungsberechtigten einholen.</p>

      <h2>5. Akzeptable Nutzung</h2>
      <p>Sie verpflichten sich:</p>
      <ul>
        <li>Den Dienst nur für persönliche und nicht-kommerzielle Zwecke zu nutzen</li>
        <li>Genaue Informationen über Ihr Gesundheitsprofil anzugeben</li>
        <li>Ihr Konto nicht mit anderen Personen zu teilen</li>
        <li>Den Dienst nicht für illegale oder nicht autorisierte Aktivitäten zu nutzen</li>
        <li>Nicht zu versuchen, die Sicherheit des Dienstes zu verletzen</li>
      </ul>

      <h2>6. Medizinischer Haftungsausschluss</h2>
      <p><strong>WICHTIG:</strong> MyWellness bietet KEINE medizinische Beratung. Die Ernährungs- und Trainingspläne werden durch künstliche Intelligenz generiert und dienen nur zu Informations- und Bildungszwecken.</p>
      <p>Konsultieren Sie vor Beginn eines Ernährungs- oder Trainingsprogramms Ihren Arzt oder einen qualifizierten Gesundheitsexperten, insbesondere wenn Sie bereits bestehende Erkrankungen haben, schwanger sind, stillen oder Medikamente einnehmen.</p>
      <p>Die Nutzung des Dienstes erfolgt auf eigenes Risiko und eigene Verantwortung.</p>

      <h2>7. Geistiges Eigentum</h2>
      <p>Alle Inhalte, Software, Code, Design, Grafiken, Logos und Materialien, die im Dienst vorhanden sind, sind ausschließliches Eigentum von VELIKA GROUP LLC und sind durch Urheberrechte, Marken und andere Gesetze zum Schutz geistigen Eigentums geschützt.</p>

      <h2>8. Haftungsbeschränkung</h2>
      <p>Im maximal gesetzlich zulässigen Umfang haftet VELIKA GROUP LLC nicht für:</p>
      <ul>
        <li>Direkte, indirekte, zufällige, Folge- oder Strafschäden</li>
        <li>Verlust von Gewinnen, Daten oder Geschäftsmöglichkeiten</li>
        <li>Körperliche Verletzungen oder Gesundheitsschäden durch die Nutzung des Dienstes</li>
        <li>Unterbrechungen oder Fehler im Dienst</li>
        <li>Inhalte oder Verhalten Dritter</li>
      </ul>

      <h2>9. Änderungen der Bedingungen</h2>
      <p>Wir behalten uns das Recht vor, diese Allgemeinen Geschäftsbedingungen jederzeit zu ändern. Änderungen werden sofort nach Veröffentlichung wirksam. Die fortgesetzte Nutzung des Dienstes nach Änderungen stellt die Akzeptanz der neuen Bedingungen dar.</p>

      <h2>10. Beendigung</h2>
      <p>Wir behalten uns das Recht vor, Ihr Konto bei Verstoß gegen diese Bedingungen ohne Vorankündigung und ohne Rückerstattung zu sperren oder zu kündigen.</p>

      <h2>11. Anwendbares Recht</h2>
      <p>Diese Bedingungen unterliegen den Gesetzen des Staates Wyoming, Vereinigte Staaten, ohne Berücksichtigung von Kollisionsnormen.</p>

      <h2>12. Kontakt</h2>
      <p>Bei Fragen zu diesen Allgemeinen Geschäftsbedingungen kontaktieren Sie uns:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>E-Mail: velika.03@outlook.it</p>
      </div>
    `
  },
  fr: {
    title: "Termes et Conditions",
    lastUpdated: "Dernière mise à jour: Janvier 2025",
    content: `
      <h2>1. Acceptation des Conditions</h2>
      <p>En accédant et en utilisant MyWellness (le "Service"), exploité par VELIKA GROUP LLC ("nous", "notre"), l'utilisateur ("vous", "votre") accepte d'être lié par ces Termes et Conditions. Si vous n'acceptez pas ces conditions, n'utilisez pas le Service.</p>

      <h2>2. Description du Service</h2>
      <p>MyWellness fournit des plans nutritionnels et d'entraînement personnalisés générés par intelligence artificielle. Le Service comprend l'analyse corporelle, le suivi des progrès, des recettes personnalisées et des routines d'entraînement.</p>

      <h2>3. Abonnements et Paiements</h2>
      <p><strong>3.1 Période d'Essai:</strong> Nous offrons une période d'essai gratuite de 3 jours. Pendant cette période, aucun frais ne sera facturé. Vous pouvez annuler à tout moment avant l'expiration de la période d'essai.</p>
      <p><strong>3.2 Renouvellement Automatique:</strong> À la fin de la période d'essai, l'abonnement se renouvellera automatiquement au plan sélectionné (Base, Pro ou Premium) avec facturation mensuelle ou annuelle selon votre choix.</p>
      <p><strong>3.3 Prix:</strong> Les prix sont affichés en Euros (€) et peuvent varier. Le prix applicable est celui affiché au moment de l'achat.</p>
      <p><strong>3.4 Annulation:</strong> Vous pouvez annuler votre abonnement à tout moment via les paramètres de votre compte. L'annulation prendra effet à la fin de la période de facturation en cours.</p>

      <h2>4. Compte Utilisateur</h2>
      <p><strong>4.1 Inscription:</strong> Pour utiliser le Service, vous devez créer un compte en fournissant des informations précises et complètes.</p>
      <p><strong>4.2 Sécurité:</strong> Vous êtes responsable de la sécurité de votre compte et de la confidentialité de vos identifiants de connexion.</p>
      <p><strong>4.3 Âge Minimum:</strong> Vous devez avoir au moins 18 ans pour utiliser le Service. Si vous avez moins de 18 ans, vous devez obtenir le consentement d'un parent ou tuteur.</p>

      <h2>5. Utilisation Acceptable</h2>
      <p>Vous acceptez de:</p>
      <ul>
        <li>Utiliser le Service uniquement à des fins personnelles et non commerciales</li>
        <li>Fournir des informations précises sur votre profil de santé</li>
        <li>Ne pas partager votre compte avec d'autres personnes</li>
        <li>Ne pas utiliser le Service pour des activités illégales ou non autorisées</li>
        <li>Ne pas tenter de violer la sécurité du Service</li>
      </ul>

      <h2>6. Avertissement Médical</h2>
      <p><strong>IMPORTANT:</strong> MyWellness ne fournit PAS de conseils médicaux. Les plans nutritionnels et d'entraînement sont générés par intelligence artificielle et sont uniquement à des fins informatives et éducatives.</p>
      <p>Avant de commencer tout programme nutritionnel ou d'exercice, consultez votre médecin ou un professionnel de santé qualifié, en particulier si vous avez des conditions médicales préexistantes, êtes enceinte, allaitez ou prenez des médicaments.</p>
      <p>L'utilisation du Service est à vos propres risques et responsabilités.</p>

      <h2>7. Propriété Intellectuelle</h2>
      <p>Tout le contenu, logiciel, code, design, graphiques, logos et matériaux présents dans le Service sont la propriété exclusive de VELIKA GROUP LLC et sont protégés par les droits d'auteur, marques et autres lois sur la propriété intellectuelle.</p>

      <h2>8. Limitation de Responsabilité</h2>
      <p>Dans la mesure maximale permise par la loi, VELIKA GROUP LLC ne sera pas responsable de:</p>
      <ul>
        <li>Dommages directs, indirects, accessoires, consécutifs ou punitifs</li>
        <li>Perte de profits, de données ou d'opportunités commerciales</li>
        <li>Blessures physiques ou dommages à la santé résultant de l'utilisation du Service</li>
        <li>Interruptions ou erreurs dans le Service</li>
        <li>Contenu ou comportement de tiers</li>
      </ul>

      <h2>9. Modifications des Conditions</h2>
      <p>Nous nous réservons le droit de modifier ces Termes et Conditions à tout moment. Les modifications seront effectives immédiatement après publication. L'utilisation continue du Service après les modifications constitue l'acceptation des nouvelles conditions.</p>

      <h2>10. Résiliation</h2>
      <p>Nous nous réservons le droit de suspendre ou de résilier votre compte en cas de violation de ces Conditions, sans préavis et sans remboursement.</p>

      <h2>11. Loi Applicable</h2>
      <p>Ces Conditions sont régies par les lois de l'État du Wyoming, États-Unis, sans égard aux principes de conflits de lois.</p>

      <h2>12. Contact</h2>
      <p>Pour des questions sur ces Termes et Conditions, contactez-nous:</p>
      <div class="contact-box">
        <p><strong>VELIKA GROUP LLC</strong></p>
        <p>30 N Gould St 32651</p>
        <p>Sheridan, WY 82801, United States</p>
        <p>EIN: 36-5141800</p>
        <p>E-mail: velika.03@outlook.it</p>
      </div>
    `
  }
};

export default function Terms() {
  const navigate = useNavigate();
  const [selectedLang, setSelectedLang] = useState('en');
  const [langMenuOpen, setLangMenuOpen] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const content = CONTENT[selectedLang];

  return (
    <div className="min-h-screen overflow-x-hidden animated-gradient-bg">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
        * { font-family: 'Inter', sans-serif; }
        :root {
          --brand-primary: #26847F;
          --brand-primary-hover: #1f6b66;
          --brand-primary-light: #e9f6f5;
        }
        .water-glass-effect {
          backdrop-filter: blur(12px) saturate(180%);
          background: linear-gradient(135deg, rgba(249, 250, 251, 0.75) 0%, rgba(243, 244, 246, 0.65) 50%, rgba(249, 250, 251, 0.75) 100%);
          box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.08), inset 0 1px 1px 0 rgba(255, 255, 255, 0.9), inset 0 -1px 1px 0 rgba(0, 0, 0, 0.05);
        }
        .content h2 { font-size: 1.5rem; font-weight: bold; color: #111827; margin-top: 2rem; margin-bottom: 1rem; }
        .content h3 { font-size: 1.25rem; font-weight: 600; color: #111827; margin-top: 1.5rem; margin-bottom: 0.75rem; }
        .content ul { list-style: disc; padding-left: 1.5rem; margin: 0.5rem 0; }
        .content li { margin: 0.5rem 0; }
        .content p { margin: 0.75rem 0; }
        .content a { color: var(--brand-primary); text-decoration: underline; }
        .contact-box { background: #f9fafb; padding: 1rem; border-radius: 0.5rem; margin-top: 1rem; }
      `}</style>

      {/* Navbar */}
      <nav className="fixed top-6 left-1/2 transform -translate-x-1/2 z-50 px-4 w-full max-w-[300px]">
        <div className="water-glass-effect rounded-full px-6 py-3 flex justify-center">
          <img
            src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68d44c626cc2c19cca9c750d/c3567e77e_MyWellnesslogo.png"
            alt="MyWellness"
            className="h-6 cursor-pointer"
            onClick={() => navigate(createPageUrl('Home'))}
          />
        </div>
      </nav>

      {/* Main Content */}
      <div className="pt-32 pb-20 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto water-glass-effect rounded-3xl p-6 sm:p-8 md:p-12">
          {/* Language Selector */}
          <div className="flex justify-end mb-6">
            <div className="relative">
              <button
                onClick={() => setLangMenuOpen(!langMenuOpen)}
                className="flex items-center gap-2 px-4 py-2 bg-white/80 hover:bg-white rounded-full border border-gray-200 transition-all">
                <Globe className="w-4 h-4 text-gray-600" />
                <span className="text-sm font-medium text-gray-700">
                  {LANGUAGES.find(l => l.code === selectedLang)?.flag} {LANGUAGES.find(l => l.code === selectedLang)?.name}
                </span>
              </button>

              {langMenuOpen && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setLangMenuOpen(false)}></div>
                  <div className="absolute right-0 top-12 bg-white rounded-2xl border border-gray-200 shadow-xl p-2 min-w-[180px] z-50">
                    {LANGUAGES.map((lang) => (
                      <button
                        key={lang.code}
                        onClick={() => {
                          setSelectedLang(lang.code);
                          setLangMenuOpen(false);
                        }}
                        className={`w-full text-left px-3 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 ${
                          selectedLang === lang.code
                            ? 'bg-[var(--brand-primary)] text-white'
                            : 'text-gray-700 hover:bg-gray-50'
                        }`}>
                        <span className="text-lg">{lang.flag}</span>
                        <span>{lang.name}</span>
                      </button>
                    ))}
                  </div>
                </>
              )}
            </div>
          </div>

          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-6 sm:mb-8">{content.title}</h1>
          <p className="text-xs sm:text-sm text-gray-500 mb-6 sm:mb-8">{content.lastUpdated}</p>

          <div 
            className="content space-y-6 sm:space-y-8 text-sm sm:text-base text-gray-700 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: content.content }}
          />
        </div>
      </div>

      {/* Footer */}
      <footer className="py-12 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center space-y-2">
            <p className="text-sm font-semibold text-gray-700">
              © VELIKA GROUP LLC. All Rights Reserved.
            </p>
            <p className="text-xs text-gray-500">
              30 N Gould St 32651 Sheridan, WY 82801, United States
            </p>
            <p className="text-xs text-gray-500">
              EIN: 36-5141800 - velika.03@outlook.it
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}